kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-from-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: basic
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-basic
