kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-basic
  annotations:
    trident.qnap.io/ThinAllocate: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: basic
