# Default values for qnap-trident.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

tridentOperator:
  image: qnapsystem/qnap-csi-operator:v1.0.0-beta
  imagePullPolicy: IfNotPresent
  debug: true

tridentOrchestrator:
  image: qnapsystem/qnap-csi:v1.0.0-beta
