apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: operator.trident.qnap.io
  name: trident-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trident-operator
subjects:
  - kind: ServiceAccount
    name: trident-operator
    namespace: {{ .Release.Namespace }}
