{{- if lt (.Capabilities.KubeVersion.Minor|int) 25 }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: operator.trident.qnap.io
  name: tridentoperatorpods
spec:
  fsGroup:
    rule: RunAsAny
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
{{- end }}
